In [1]:
import numpy as np

In [3]:
matrix_A = np.array([[1,2], [3,4]])
print("Matrix A:\n", matrix_A)

reshaped_matrix = np.reshape(matrix_A, (4,1))
print("Reshaped Matrix:\n", reshaped_matrix)

matrix_A[0,0] = 5
print("Updated Matrix A:\n", matrix_A)


Matrix A:
 [[1 2]
 [3 4]]
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]]
Updated Matrix A:
 [[5 2]
 [3 4]]


In [6]:
# Movie ratings matrix (5 viewers, 3 movies)
movie_ratings = np.array([
    [5, 1, 4],
    [4, 4, 2],
    [4, 3, 5],
    [1, 1, 5],
    [3, 2, 1]
])

# Average rating per movie
average_rating = np.mean(movie_ratings, axis=0)
viewer_preference = np.max(movie_ratings, axis=1)
print("Average Rating:\n", average_rating)
print("Viewer preference:\n", viewer_preference)

Average Rating:
 [3.4 2.2 3.4]
Viewer preference:
 [5 4 5 5 3]


In [7]:
# Define two matrices
matrix_B = np.array([[2, 3], [4, 5]])
matrix_C = np.array([[1, 1], [1, 1]])

# Adding and subtracting matrices
sum_matrix = np.add(matrix_B, matrix_C)
diff_matrix = np.subtract(matrix_B, matrix_C)

print("Sum of Matrices:\n", sum_matrix)
print("Difference of Matrices:\n", diff_matrix)

Sum of Matrices:
 [[3 4]
 [5 6]]
Difference of Matrices:
 [[1 2]
 [3 4]]


In [8]:
# Multiplication of two matrices
prod_matrix = np.dot(matrix_B, matrix_C)
print("Product of Matrices:\n", prod_matrix)

Product of Matrices:
 [[5 5]
 [9 9]]


In [9]:
# Defining matrices
price_matrix = np.array([[10, 15],
                         [12, 18]])
quantity_matrix = np.array([[30, 40],
                            [25, 35]])

# Multiplying matrices to get total sales
total_sales_matrix = np.dot(price_matrix, quantity_matrix.T)

print("Total Sales Matrix:\n", total_sales_matrix)

Total Sales Matrix:
 [[ 900  775]
 [1080  930]]


In [11]:
# Temperature data matrix (4 cities, 7 days)
temperature_data = np.array([
    [27, 20, 15, 18, 26, 18, 22],
    [24, 18, 20, 17, 19, 22, 21],
    [23, 23, 27, 25, 16, 21, 22],
    [22, 29, 23, 16, 20, 24, 28]
])

average_temp = np.mean(temperature_data, axis=1)
max_ciy_temp = np.max(temperature_data, axis=1)
min_city_temp = np.min(temperature_data, axis=1)

day_7_temp = temperature_data[:,6]
day_1_temp = temperature_data[:,0]
temp_diff = day_7_temp - day_1_temp
print("Temperature change (Day 7 - Day 1):", temp_diff)

Temperature change (Day 7 - Day 1): [-5 -3 -1  6]


In [12]:
# Creating date ranges
dates = np.arange('2020-01', '2020-02', dtype='datetime64[D]')
print("January 2020 Dates:\n", dates)

January 2020 Dates:
 ['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30'
 '2020-01-31']


In [13]:
# Converting dates to a different format
formatted_dates = np.datetime_as_string(dates, unit='D')
print("Formatted Dates:\n", formatted_dates)

Formatted Dates:
 ['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30'
 '2020-01-31']


### Class Exercises

In [36]:
# All imports for today's lecture
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
%matplotlib inline
plt.rcParams['figure.figsize'] = (10, 6)
plt.style.use('seaborn-v0_8-whitegrid')

# Set a seed for reproducibility
np.random.seed(42)

print(f"NumPy version: {np.__version__}")
print("All libraries loaded! Ready for Day 2.")

NumPy version: 2.3.5
All libraries loaded! Ready for Day 2.


In [37]:
# Load dataset for today's examples
tips = sns.load_dataset('tips')
total_bills = tips['total_bill'].values
tip_amounts = tips['tip'].values

print("Tips dataset loaded!")
print(f"Shape: {tips.shape}")
print(f"total_bills: {total_bills[:5]}  (first 5)")
print(f"tip_amounts: {tip_amounts[:5]}  (first 5)")

Tips dataset loaded!
Shape: (244, 7)
total_bills: [16.99 10.34 21.01 23.68 24.59]  (first 5)
tip_amounts: [1.01 1.66 3.5  3.31 3.61]  (first 5)


In [38]:
# Warm-Up - Boolean indexing from yesterday
small_tips = tip_amounts[tip_amounts < 2.0]  # tips less than $2.00
print(f"Tips under $2: {small_tips}")
print(f"Count: {len(small_tips)}")
print(f"Mean: ${small_tips.mean():.2f}")

Tips under $2: [1.01 1.66 1.96 1.71 1.57 1.67 1.45 1.32 1.56 1.5  1.76 1.98 1.   1.97
 1.25 1.83 1.   1.5  1.5  1.64 1.   1.5  1.8  1.68 1.48 1.5  1.5  1.25
 1.5  1.36 1.63 1.73 1.61 1.5  1.44 1.1  1.5  1.44 1.92 1.58 1.47 1.25
 1.   1.17 1.75]
Count: 45
Mean: $1.50


In [39]:
#Exercise - Statistical Analysis 
np.random.seed(42)
data = np.random.normal(loc=100, scale=15, size=50) # normal distribution: mean=100, std=15, 50 values

mean_val = np.mean(data)
median_val = np.median(data)
std_val = np.std(data)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print(f"Mean:    {mean_val:.2f}")
print(f"Median:  {median_val:.2f}")
print(f"Std Dev: {std_val:.2f}")
print(f"Q1 (25th): {q1:.2f}")
print(f"Q3 (75th): {q3:.2f}")

Mean:    96.62
Median:  96.49
Std Dev: 13.86
Q1 (25th): 87.09
Q3 (75th): 105.04


In [40]:
# Exercise - Matrix Operations
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# 1. Determinant
# Determinant tells us if the matrix is healthy. No redundant columns, the same, duplicate, multiplication of another column
det_A = np.linalg.det(A)
print(f"Determinant: {det_A:.2f}")

# 2. Inverse
# The inverse of the matrix. If we multiply the matrix by the inverse we get the identity
A_inv = np.linalg.inv(A)
print("\nInverse:")
print(A_inv.round(4))

# 3. Verify
product = A @ A_inv
print(f"\nIs identity? {np.allclose(product, np.eye(3))}")

Determinant: 1.00

Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Is identity? True


In [41]:
# Exercise - Array Comparison
np.random.seed(42)
array_1 = np.random.randint(1, 100, 10)
array_2 = np.random.randint(1, 100, 10)

print(f"Array 1: {array_1}")
print(f"Array 2: {array_2}")

# Element-wise comparison
comparison = array_1 > array_2
print(f"\nArray 1 > Array 2: {comparison}")
print(f"Count where Array 1 is greater: {comparison.sum()} out of {len(comparison)}")

Array 1: [52 93 15 72 61 21 83 87 75 75]
Array 2: [88 24  3 22 53  2 88 30 38  2]

Array 1 > Array 2: [False  True  True  True  True  True False  True  True  True]
Count where Array 1 is greater: 8 out of 10


In [42]:
# Exercise - Date Manipulation
january = np.arange('2023-01-01', '2023-02-01', dtype='datetime64[D]')  # all dates in January 2023
formatted = np.char.replace(january.astype(str), '-', '/')  # convert to YYYY/MM/DD format

print(f"January 2023 ({len(january)} days)")
print(f"\nFirst 5: {formatted[:5]}")
print(f"Last 5:  {formatted[-5:]}")

January 2023 (31 days)

First 5: ['2023/01/01' '2023/01/02' '2023/01/03' '2023/01/04' '2023/01/05']
Last 5:  ['2023/01/27' '2023/01/28' '2023/01/29' '2023/01/30' '2023/01/31']


In [43]:
# Exercise - Time Series Manipulation
np.random.seed(99)

dates = np.arange('2023-01-01', '2024-01-01', dtype='datetime64[D]')
prices = 50 + np.cumsum(np.random.normal(0, 1.5, len(dates)))

quarters = [
    ("Q1: Jan-Mar", '2023-01-01', '2023-04-01'),
    ("Q2: Apr-Jun", '2023-04-01', '2023-07-01'),
    ("Q3: Jul-Sep", '2023-07-01', '2023-10-01'),
    ("Q4: Oct-Dec", '2023-10-01', '2024-01-01'),
]

for name, start, end in quarters:
    mask = ((dates >= np.datetime64(start)) & (dates <= np.datetime64(end)) )  # boolean mask for this quarter
    q_data = prices[mask]
    print(f"{name}: Mean={q_data.mean():.2f}, Min={q_data.min():.2f}, Max={q_data.max():.2f}")

Q1: Jan-Mar: Mean=53.12, Min=48.54, Max=57.44
Q2: Apr-Jun: Mean=69.33, Min=51.78, Max=81.72
Q3: Jul-Sep: Mean=58.44, Min=51.48, Max=67.94
Q4: Oct-Dec: Mean=71.91, Min=63.50, Max=79.46


1. Data Creation Exercise:

Objective: Create a simulated time series dataset.

Instructions:
* Generate a date range from January 1, 2022, to December 31, 2022, with a daily frequency.
* Simulate daily temperature data for this period. Assume temperature varies between 10°C and 35°C.
* Simulate daily humidity data for the same period. Assume humidity varies between 30% and 90%.
* Structure the data into a DataFrame with columns: Date, Temperature, and Humidity.

In [44]:
dates_2022 = np.arange('2022-01-01', '2023-01-01', dtype='datetime64[D]')

temps = np.random.uniform(10,35, size=len(dates))
humidity = np.random.uniform(30, 90, size=len(dates))

dtype = [('Date', 'datetime64[D]'), ('Temperature', 'f4'), ('Humidity', 'f4')]
weather_data = np.zeros(len(dates), dtype=dtype)

weather_data['Date'] = dates_2022
weather_data['Temperature'] = temps
weather_data['Humidity'] = humidity

print(weather_data[:5])

[('2022-01-01', 15.55055 , 88.865395) ('2022-01-02', 17.090183, 46.874588)
 ('2022-01-03', 20.839664, 85.86352 ) ('2022-01-04', 23.387518, 68.21822 )
 ('2022-01-05', 31.04942 , 62.001766)]


2. Data Analysis Exercise:

Objective: Perform basic data analysis on the time series data.

Instructions:
* Calculate the mean, median, and standard deviation for both temperature and humidity.
* Identify the date with the highest temperature and the date with the highest humidity.
* [bonus] Plot the temperature and humidity trends over the year.

In [ ]:
temp_mean = np.mean(weather_data['Temperature'])
temp_median = np.median(weather_data['Temperature'])
temp_std = np.std(weather_data['Temperature'])

humidity_mean = np.mean(weather_data['Humidity'])
humidity_median = np.median(weather_data['Humidity'])
humidity_std = np.std(weather_data['Humidity'])

print(f"Temp Mean: {temp_mean:.2f}, Median: {temp_median:.2f}, Std: {temp_std:.2f}")
print(f"Humidity Mean: {humidity_mean: .2f}, Median: {humidity_median: .2f}, std: {humidity_std:.2f}")

max_temp_idx = np.argmax(weather_data['Temperature'])
max_temp_date = weather_data['Date'][max_temp_idx]

max_hum_idx = np.argmax(weather_data['Humidity'])
max_hum_date = weather_data['Date'][max_hum_idx]





3. Window Function Exercise:

Objective: Apply window functions to the time series data.

Instructions:
* Use a rolling window of 7 days to calculate the moving average for both temperature and humidity.
* [bonus] Plot the original data and the 7-day moving average on the same graph for comparison.

In [48]:
# Convert the numpy data into a dataframe for pandas
df = pd.DataFrame(weather_data)
# set the date as the index, for the time series power
df.set_index('Date', inplace=True)

df['Temp_7Day_Avg'] = df['Temperature'].rolling(window=7).mean()
df['Humidity_7Day_Avg'] = df['Temperature'].rolling(window=7).mean()

print(df[['Temperature', 'Temp_7Day_Avg']].head(10))

            Temperature  Temp_7Day_Avg
Date                                  
2022-01-01    15.550550            NaN
2022-01-02    17.090183            NaN
2022-01-03    20.839664            NaN
2022-01-04    23.387518            NaN
2022-01-05    31.049419            NaN
2022-01-06    21.224960            NaN
2022-01-07    21.938023      21.582903
2022-01-08    12.816865      21.192376
2022-01-09    32.765171      23.431660
2022-01-10    17.797846      22.997115
