In [1]:
import numpy as np

### Practice: Exercise 1

In [3]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
int_arr = np.array([1,2,3])
print(f"Integegr array: {int_arr}, dtype: {int_arr.dtype}")

float_arr = np.array([1.5,2.7,3.14])
print(f"Float array: {float_arr}, dtype: {float_arr.dtype}")

mixed = np.array([1,2,3.14])
print(f"Mixed input: {mixed}, dtype: {mixed.dtype}")

int_arr_converted_float = int_arr.astype('float')
print(int_arr_converted_float)

Integegr array: [1 2 3], dtype: int64
Float array: [1.5  2.7  3.14], dtype: float64
Mixed input: [1.   2.   3.14], dtype: float64
[1. 2. 3.]


### Practice: Exercise 2
Convert a Python list of floats [1.5, 2.7, 3.9, 4.1, 5.8] into a NumPy array of integers.

Hint: Create the array with np.array(), then use .astype(int).

Note: .astype(int) truncates (cuts off decimals), it does NOT round.

Expected output: array([1, 2, 3, 4, 5])

Time: 2 minutes

In [7]:
float_list = [1.5, 2.7, 3.9, 4.1, 5.8]
arr = np.array(float_list).astype(int)

print(arr)
print(f"dtype: {arr.dtype}")


[1 2 3 4 5]
dtype: int64


### Practice: Exercise 3
Create a 3x3 NumPy array containing the values 1 through 9.

Hint: Use np.array() with a list of three lists: [[1,2,3], [4,5,6], [7,8,9]].

Expected output:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
Time: 2 minutes

In [ ]:
list_lists = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(list_lists)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Practice: Exercise 4
Create a 4x4 identity matrix using np.eye().

Expected output:

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
Time: 1 minute

In [9]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Practice: Exercise 5

In [11]:
arr = np.array([10, 20, 30, 40, 50])
reverse = arr[::-1]
print(reverse)

[50 40 30 20 10]


### Practice: Exercise 6
Create a 2D array with values 1-12 shaped as 3 rows and 4 columns. Then select the second row.

Hint: Use np.array() with three lists: [[1,2,3,4], [5,6,7,8], [9,10,11,12]]. Then index with [1] for the second row.

Expected output for the array:

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
Expected output for second row: array([5, 6, 7, 8])

Time: 2 minutes

In [13]:
matrix = np.array([[1,2,3,4],
                   [5,6,7,8], 
                   [9,10,11,12]
                   ])

print(f"Second row: {matrix[1]}")


Second row: [5 6 7 8]


In [15]:
matrix_1d = np.arange(1,13)
print(matrix_1d)

# A faster way to print the 2D array above
matrix_2d = np.arange(1,13).reshape(3,4)
print(matrix_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercise 7

In [19]:
matrix = np.arange(1,21)
matrix_2 = matrix.reshape(4,5)
print(matrix)
print(matrix_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Exercise 8

In [27]:
arr = np.array([10, 20, 30, 40, 50])
print(f"Array: {arr}")
print(f"Sum: {arr.sum()}")
print(f"Avg: {arr.mean()}")


Array: [10 20 30 40 50]
Sum: 150
Avg: 30.0


In [28]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])

[47 43 35 47]


In [29]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([3, 1, 4, 6, 7, 5, 2])

In [30]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[1, 2],
       [5, 6],
       [3, 4]])

In [32]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [33]:

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [34]:
# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [35]:
# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]
